### ISSUE TITLE
Roadmap for Module 7 (previously Module 8)

### ISSUE THREAD

**Issue by mgelbart** [UBC-MDS/programming-in-python-for-data-science#43]
We could put in "abstracting functions and tests to other files" here - want to make sure there's a good way of doing other files though, from a technical perspective - let's ask Tiffany. So the assignment could be something like this:

1. (Mike lead) A question on importing libraries 
    - there is content you can take from DSCI 511 
    - we can keep this pretty short, don't need to be that thorough 
    - we are already using `import pandas as pd` so we should cover `as`
    - not sure if we need `from` 
2. (Tiffany lead) Working with other files - moving functions there 
    - provide them with the function and the tests
    - ideally some code they've already written previously
    - they will need to import their own file
    - `import my_file` and then `my_file.my_func` (if we don't teach `from`)
    - they can run `?` in Jupyter and see the docstring coming from the other file
3. (Tiffany lead) Working with other files - moving tests there & pytest
    - take some tests, move them
    - opening a terminal in jupyter lab (or can this be done from the notebook?? `!pytest`)
    - running pytest
4. (Mike lead) Correct some given code's style to adhere to a style guide - the part that can be automatically checked (whitespace, variable names)
    - Also some MCQs about why the original code would make life hard. 
    - Let's use black style guide instead of pep8 since that's what we're switching to for DSCI 511 (you can ask Tom if you have questions). 
    - Have them press the button in Jupyter lab to auto-format
5. (Mike lead) Correct some given code's style to adhere to a style guide - the part that can NOT be automatically checked (magic numbers, quality of comments, variable names adhering to style but not making sense)
    - and again some MCQs about why it is bad
6.  (Unknown lead) Python debugger

**Comment by hfboyce** [comment]
@ttimbers Regarding the functions for Section 2, 3: 

Here is a function introduced in Module 6 to explain helper data.

```
def column_stats(df, column):
   stats_dict = {'max': df[column].max(),
                 'min': df[column].min(),
                 'mean': round(df[column].mean()),
                 'range': df[column].max() - df[column].min()}
   return stats_dict

```

This was the helper data we used 

```
data = { 'name': ['Cherry', 'Oak', 'Willow', 'Fir', 'Oak'], 
         'height': [15, 20, 10, 5, 10], 
         'diameter': [2, 5, 3, 10, 5], 
         'age': [0, 0, 0, 0, 0], 
         'flowering': [True, False, True, False, False]}
         
forest = pd.DataFrame.from_dict(data)
forest
```

And these were the tests:

```
assert column_stats(forest, 'height') == {'max': 20, 'min': 5, 'mean': 12.0, 'range': 15}
assert column_stats(forest, 'diameter') == {'max': 10, 'min': 2, 'mean': 5.0, 'range': 8}
assert column_stats(forest, 'age') == {'max': 0, 'min': 0, 'mean': 0, 'range': 0}
```

You also could use this function that we have been building on so they will be very familiar with it. 


```
def exponent_a_list(numerical_list, exponent=2):
        """
    Creates a new list containing the square values of the input list. 
    
    Parameters
    ----------
    numerical_list : list
        The list from which to calculate squared values 
        
    Returns
    -------
    list
        A new list containing the squared value of each of the elements from the input list 

    Raises
    ------
    TypeError
        If the input argument numerical_list is not of type list

    Examples
    --------
    >>> squares_a_list([1, 2, 3, 4])
    [1, 4, 9, 16]

    """
    if not isinstance(numerical_list, list):
        raise TypeError("You are not using a list for the numerical_list input.")

    if not all(type(element) is int for element in numerical_list):
        raise TypeError("The elements in numerical_list must all be of type int")

    new_exponent_list = list()
    for number in numerical_list:
        new_exponent_list.append(number ** exponent)
    return new_exponent_list

```

And we used the following tests: 

```
assert exponent_a_list([1, 2, 4, 7], 2) == [1, 4, 16, 49], "incorrect output for exponent = 2"
assert exponent_a_list([1, 2, 3], 3) == [1, 8, 27], "incorrect output for exponent = 3"
assert exponent_a_list([], 3) == [], "incorrect output for empty list"
assert exponent_a_list([0, 1, 3], 0) == [1, 1, 1], "incorrect output for exponent 0"
assert exponent_a_list([1, 2], -2) == [1, 0.25], "incorrect output for a negative exponent"
```

**Comment by hfboyce** [comment]
Proposing: 
4. Black, flake8 style guide
- Slides explaining flake8 and what it catches 
- In screencast show first flake 8 finding the problems, then show Jupyter extension fixing the code. Re run- flake 8 on the already adjusted code which omits long variable name changes, hardcoding and variables that are not used. This now segues into section 5 well. 
5. No screencast needed for this part. 
6. Python debugger -> screencast and slides with images. ( this would be relatively quick to explain and put in at the end)

**Comment by hfboyce** [comment]
Aspect Ratio for screencasts ->  920 x 1080

**Comment by ttimbers** [comment]
Are you sure that 920 x 1080 is the aspect ratio and not 1920 x 1080? I cannot find anyone on the internet talking about or using a 920 x 1080 aspect ratio.

**Comment by ttimbers** [comment]
So it's really a 16:9 aspect ratio, with size width=1920 and height=1080? Can you please confirm this @hfboyce ?

**Comment by ttimbers** [comment]
Another term for this is 1080p.

**Comment by hfboyce** [comment]
Ok I sent Aika an email back. These are the dimensions that I was told so, I'll double check if 1080p (1920 X 1080) is what she meant.

**Comment by ttimbers** [comment]
I've also created a demo where I went to great effort to scale my mac's aspect ratio to 1080p, and then also exported the video as 1080p. Can you send it to the producer/XL team and ask if this is what will work with what they are doing. *Note: there is a little glitch I had to cut out where the kernel stalled on me, so its not a high quality teaching video, but it gives an example of the flavour and filetype we would be creating. Also, what filetype should I save these as? mp4 (that is what I have uploaded here, but zipped to allow for upload)? something else? Who's doing the editing of sticking all these together (the videos we film on Friday and the screencasts we create ourselves)?

[test.mp4.zip](https://github.com/UBC-MDS/MCL-DSCI-011-programming-in-python/files/5120014/test.mp4.zip)

**Comment by ttimbers** [comment]
For the record, I did the following three things to try to ensure 1080p:

1. Installed [SwitchResX](https://www.madrau.com/) so I could actually choose the display used by my Mac, and set it to 1920 X 1080 (1080p) 
2. Set the project settings inside Camtasia to 1080p (https://blogs.shu.ac.uk/l3sstaff/files/2018/09/DT-Camtasia-9-Aspect-Ratio.pdf)
3. When I outputted the file from Camtasia, I did it via Share > Local File > Options and then set Dimensions to 1902 x 1080 HD (see pic below)

**Comment by hfboyce** [comment]
> Can you send it to the producer/XL team and ask if this is what will work with what they are doing.
I'll ask Aika for his email directly I think and have a meeting with him. 

> Also, what filetype should I save these as? mp4 (that is what I have uploaded here, but zipped to allow for upload)? 
I think Mp4 is fine since they are all going to be edited together and put into a youtube video but I'll ask him in the meeting I'm setting up.  I think mp4 is fine but I'll update you when I know more. 

> Who's doing the editing of sticking all these together (the videos we film on Friday and the screencasts we create ourselves)
This is being done by the producer. He knows that we will have additional screencasts that we will need to put into the video  already and he and I will discuss the ordering.

**Comment by ttimbers** [comment]
> I'll ask Aika for his email directly I think and have a meeting with him.

💯  ❗

**Comment by ttimbers** [comment]
Hopefully you can do this soon? And then perhaps I should wait again on doing the screencast until we know more? This pre-research has been helpful but I don't want to record them twice.

**Comment by hfboyce** [comment]
I just sent an email so lets cross our fingers.
