### ISSUE TITLE
Roadmap for Module 8

### ISSUE THREAD

**Issue by mgelbart** [UBC-MDS/programming-in-python-for-data-science#44]
1. Debug some very buggy code using the debugger 
    - Mike can help design question - basically just some code full of bugs
    - Tom probably has [a new lecture on this](https://pages.github.ubc.ca/MDS-2020-21/DSCI_511_py-prog_instructors/lectures/lecture3-tests-classes.html#the-python-debugger-pdb-10-min)
    - A bit of this in 524 as well

**Comment by hfboyce** [comment]
## ASSIGNMENT ROADMAP


### datetime Question 
- 330: assignment 1b (Are the measurements equally spaced?) 
- Sneak in a few simple ones on a dataframe


#### strings 

- [Python version of some of these](https://github.com/rstudio/cheatsheets/blob/master/strings.pdf)
- Look at Julian's [lecture](https://github.com/UBC-MDS/COLX_521_corp-ling_students/blob/master/complete_lectures/Lecture1_strings.ipynb) 


## Numpy 

- Un related tom question questions (from lab 3 523) 
- Relationship between countries -> make into a new dataframe with diagonals as `nan`. 

```python
n = len(countries)
countries[range(n), range(n)] = np.nan
```

Sets all diagonal elements to nan
- Countries [dataframe](https://www2.stat.duke.edu/courses/Spring18/Sta199/appex/00-unvotes.html) 
- pandas profilling to 


## drop NA

- df.dropna()) or replacing (df.fillna()).


## Dirty Gapminder question from lab 4 

- [lab 4](https://github.ubc.ca/MDS-2019-20/DSCI_523_data-wrangling_students/blob/master/labs/solutions/lab4/lab4.ipynb)

**Comment by hfboyce** [comment]
## Content Ideas 

### strings 

- [Python version of some of these](https://github.com/rstudio/cheatsheets/blob/master/strings.pdf)
- Look at Julian's [lecture](https://github.com/UBC-MDS/COLX_521_corp-ling_students/blob/master/complete_lectures/Lecture1_strings.ipynb) 


## drop NA

- df.dropna()) or replacing (df.fillna()).

**Comment by hfboyce** [comment]
## Content Roadmap

1, Numpy
 - Why NumPy? How it relates to pandas 
- np.pi and values and functions.  


2. 
- shapes 
- ndarray 
- 1d, 2d, 
- x.shape is blank what is x.ndim going to be and what is x.size
- indexing, access the 3rd row 2nd column example 
- np.diff() pure number crunching 

3. Dealing with Null/NaN values 
- df.info 
-  null is our for but it's really np.nan 
- fillna, dropna 
-np.isnan

4. Date time 

-Parsing data yourself -> HARD!  DO NOT DO IT
- Appreciation for pandas datetime
- pd.read_csv() parse_date 
- .day, .month , 
- Mention Python Datetime (similar to numpy to pandas, datetime to Datetime64) 
- subtracting date  timedelta. (link to documentation (to seconds function, to days etc)  
- diff() for datetime 
- dt.day_name()  -> Weekday name 

 5. Strings  

- .str.strip()
- str.replace()
- review upper(), lower(), count(), split(), (concatenation +, slicing, ) 
- -multiplying by an integer 

6. Strings 

-join()
- Additional functions here 
is shorter string in longer string 
- contains vs in 
- .find
