### ISSUE TITLE
Module 7 

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/programming-in-python-for-data-science#59]
Check out the new logo ;) 
https://prog-learn.mds.ubc.ca/ 
Hi Mike here are the slide decks for module 7. I'll be making the questions this afternoon. 
The decks are:
- 7.01
- 7.11 (this has empty slides to account for the screen shots of the recording, that will be put in) 
- 7.14

I'll tag you once the questions are done! 
Thanks!

**Comment by mgelbart** [comment]
- 7.11.3: I was surprised to see PEP8 mentioned. I thought we were using Black instead? That is, I think Black is both a style (replacing PEP8) and a formatter. Am I mistaken? 
- 7.11.4: I would prefer to use a different function that is more data science-y. Wish list?
- 7.14.2: Obtaining the cereal -> Obtaining the cereals
- 7.14.3: Here it makes sense to mention PEP8 since I think PEP8 covers this type of thing and Black doesn't. ;; when writing comment -> when writing comments
- 7.14.4: This is cut off at the bottom for me
- 7.14.6: I think we can be more specific in the transcript about what the problem is: if you try to use that keyword for its intended functionality, it will throw an error because it will try to use your variable instead. 
- 7.14 in general: I really liked the examples you chose of good/bad comments. Great stuff. The bad comments and variable names were fun.

**Comment by hfboyce** [comment]
Thank you! 

I kinda have to mention PEP8 because of flake8 though? 

Can you take a quick look at 7.01 too please?

**Comment by hfboyce** [comment]
@mgelbart Mike please see my comments above. 

I have pushed the questions for module 7!! Let me know what you think. Thanks

**Comment by mgelbart** [comment]
> I kinda have to mention PEP8 because of flake8 though?

Can you elaborate on this? What is the relationship between these two? I do think it makes sense to mention it in 7.14.3 but not in 7.11.3.

**Comment by mgelbart** [comment]
By 7.0.1 you mean the learning objectives right? I would change "check your tests" to "run your tests" and "rectify your code" to "debug your code".

**Comment by mgelbart** [comment]
I opened up the questions and the first one has a typo:

> How would you import a package name `numpy`?

I think Tiffany's suggestion is a good one - can you read them aloud and make any necessary changes and then I'll review?

**Comment by hfboyce** [comment]
flake8 tells you where your code does not follow PEP8 stylizing but Black has some other formatting things it adheres to like  code length is 88 characters, not 79.

7.01 -> importing Python libraries

I'm reading that aloud and I'm not sure where the typo is. I think I am going crazy.

**Comment by hfboyce** [comment]
Ok I read them over and hopefully caught more 😩.

**Comment by hfboyce** [comment]
Ok I read them over and hopefully caught more 😩. 
Give it 5 minutes to reflect and refresh!

**Comment by mgelbart** [comment]
Great, I'll take a look soon. Regarding

> flake8 tells you where your code does not follow PEP8 stylizing but Black has some other formatting things it adheres to like code length is 88 characters, not 79.

My impression is that flake8 can work with whatever style guide you want, be it PEP8 or Black, and that we decided to use Black as opposed to PEP8. But I am not quite sure. It may be worth confirming with Tom on this.

**Comment by hfboyce** [comment]
This is flake8 
https://pypi.org/project/flake8/

We can get flake8 WITH black but it's a separate installation
https://pypi.org/project/flake8-black/

In Tom's lecture he uses just Flake8
https://pages.github.ubc.ca/MDS-2020-21/DSCI_511_py-prog_students/lectures/lecture4-style-scripts-imports.html#linters

I can update the assignment and dockerfile to use `flake8-black`?

**Comment by mgelbart** [comment]
- Ex 4: mention the name `power7_5` in the instructions
- Ex 10: checked -> checks;; make a new sentence starting at How
- Ex 11: so we still have BMI? Is it on the wishlist?  ;; Tiffany should review this exercise
- Ex 14: confusing about the title "Using Black" - do they use Black here? ;; why does the solution have no blank line after the `import`? 
- Ex 16: the question is missing?;; I think "no comment needed" could also be a valid correct answer.

-

**Comment by mgelbart** [comment]
About PEP8 vs. Black, can you write up some info about this in a Slack thread with Tiff and Tom so we can get input from them?

**Comment by hfboyce** [comment]
> - Ex 11: so we still have BMI? Is it on the wishlist?  ;; Tiffany should review this exercise

Currently it's on the wishlist I'll change this to for Force = Mass *Acceleration instead. 

All other comments addressed. Thank you.
